"""Validate repository commit messages against the project convention."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ALLOWED_TYPES = (
    "feat",
    "fix",
    "refactor",
    "perf",
    "test",
    "docs",
    "build",
    "ci",
    "chore",
    "data",
    "exp",
)
REQUIRED_SECTIONS = (
    "背景与目的：",
    "改动内容：",
    "验证方式与结果：",
    "实验与数据影响：",
    "关联事项：",
)
REQUIRED_FIELDS = (
    "命令：",
    "结果：",
    "数据集/配置：",
    "指标或结果：",
    "可复现性影响：",
    "Issue/任务：",
    "BREAKING CHANGE：",
)
SUBJECT_PATTERN = re.compile(
    rf"^({'|'.join(ALLOWED_TYPES)})\([a-z0-9][a-z0-9._/-]*\)(!)?: (.+)$"
)
AUTOGENERATED_PREFIXES = ("Merge ", "Revert \"", "fixup! ", "squash! ")


def _content_lines(message: str) -> list[str]:
    return [line.rstrip() for line in message.splitlines() if not line.startswith("#")]


def _field_value(lines: list[str], field: str) -> str | None:
    for line in lines:
        stripped = line.strip()
        candidate = stripped[2:].strip() if stripped.startswith("- ") else stripped
        if candidate.startswith(field):
            return candidate[len(field) :].strip()
    return None


def validate_message(message: str) -> list[str]:
    """Return validation errors; an empty list means the message is valid."""

    lines = _content_lines(message)
    nonempty = [line.strip() for line in lines if line.strip()]
    if not nonempty:
        return ["commit message is empty"]

    subject = nonempty[0]
    if subject.startswith(AUTOGENERATED_PREFIXES):
        return []

    errors: list[str] = []
    match = SUBJECT_PATTERN.fullmatch(subject)
    if not match:
        errors.append(
            "subject must match '<type>(<scope>): <summary>' with an allowed type"
        )
    else:
        summary = match.group(3).strip()
        if summary.endswith((".", "。")):
            errors.append("subject summary must not end with a period")
        if "<" in summary or ">" in summary:
            errors.append("subject still contains template placeholders")

    if len(subject) > 72:
        errors.append("subject must be 72 characters or fewer")

    positions: list[int] = []
    for section in REQUIRED_SECTIONS:
        occurrences = [index for index, line in enumerate(lines) if line.strip() == section]
        if len(occurrences) != 1:
            errors.append(f"required section must appear exactly once: {section}")
        else:
            positions.append(occurrences[0])
    if len(positions) == len(REQUIRED_SECTIONS) and positions != sorted(positions):
        errors.append("required sections are not in template order")

    for field in REQUIRED_FIELDS:
        value = _field_value(lines, field)
        if value is None:
            errors.append(f"required field is missing: {field}")
        elif not value:
            errors.append(f"required field has no value: {field}")

    for section in REQUIRED_SECTIONS[:2]:
        if section in lines:
            start = lines.index(section) + 1
            end_candidates = [
                lines.index(next_section)
                for next_section in REQUIRED_SECTIONS
                if next_section in lines and lines.index(next_section) > start
            ]
            end = min(end_candidates, default=len(lines))
            body = [
                line.strip().removeprefix("- ").strip()
                for line in lines[start:end]
                if line.strip()
            ]
            if not body or all(item in {"", "无"} for item in body):
                errors.append(f"section requires a meaningful description: {section}")

    return errors


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")

    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("Usage: validate_commit_message.py <commit-message-file>", file=sys.stderr)
        return 2

    message_path = Path(args[0])
    message = message_path.read_text(encoding="utf-8-sig")
    errors = validate_message(message)
    if not errors:
        return 0

    print("ERROR: commit message does not follow CONTRIBUTING.md:", file=sys.stderr)
    for error in errors:
        print(f"  - {error}", file=sys.stderr)
    print("\nRun 'git commit' and complete every field in .gitmessage.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
